language: perl
perl:
   - 'blead'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
matrix:
   allow_failures:
      - perl: 'blead'
   fast_finish: true
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 AUTHOR_TESTING=0
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - cpanm --quiet --notest --skip-satisfied Test::Perl::Critic Test::Spelling Test::NoTabs Test::EOL Carp Clone Data::Validate::URI File::Basename Getopt::Long HTTP::Headers HTTP::Request HTTP::Response IO::Interactive::Tiny JSON::XS LWP::UserAgent Scalar::Util TAP::Harness TAP::Parser Term::ANSIColor Test::LWP::UserAgent Try::Tiny Types::Serialiser
branches:
   only:
      - /^build/
